### ISSUE TITLE
Crear componente carrusel

### ISSUE THREAD

**Issue by Facu00H** [Facu00H/mytinenrary-hernando-alvarez#8]
- Debe tener un titulo "PopularMytineraries".
- Debe contener 3 Slides de 4 fotos cada una / son 12 ciudades repartidas en 3 slides de 4 c/u.
- Cada foto debe corresponde a una ciudad del mundo y debe estar su nombre en ingles.
- Como no disponemos de bases de datos, las fotos/nombres van a estar hardcodeados en los componentes.
- El renderizado debe ser DINAMICO.

**Comment by Joaquinbrialva** [comment]
Carousel created, remains arrows and animations to do.
